# Generated by Django 5.1.3 on 2024-11-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rippleet',
            old_name='last_modified',
            new_name='updated_at',
        ),
    ]
