# Generated by Django 5.1.3 on 2024-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0002_rename_last_modified_rippleet_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rippleet",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
