# Generated by Django 5.1.3 on 2024-11-28 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0004_alter_rippleet_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rippleet",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_rippleets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
