services:
  backend:
    build:
      context: ./backend  # Path to your backend folder
    container_name: ripple_app_backend
    ports:
      - "8000:8000"  # Maps container's port to localhost
    volumes:
      - ./backend:/app  # Keeps backend code synced during development
      - static_volume:/app/staticfiles  # Shared volume for static files
    env_file:
      - ./backend/env.dev  # Environment variables for Django
    environment:
      - DJANGO_DEBUG=False
    depends_on:
      - db  # Ensures db service is up before backend starts

  nginx:
    image: nginx:latest
    container_name: ripple-nginx
    ports:
      - "80:8080"  # Nginx serves on port 80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Custom Nginx configs
      - static_volume:/app/staticfiles  # Share static files
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    container_name: ripple_app_frontend
    ports:
      - "5173:5173"  # Expose Vite dev server
    volumes:
      - ./frontend:/app  # Sync frontend code
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:13  # PostgreSQL version of choice
    container_name: ripple_app_db
    ports:
      - "5435:5432"  # Maps PostgreSQL default port
    environment:
      POSTGRES_USER: ripple_dev
      POSTGRES_PASSWORD: ripple_dev
      POSTGRES_DB: ripple_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:
  static_volume: